services:
  # Qdrant Vector Database
  qdrant:
    image: qdrant/qdrant:v1.7.0
    container_name: qdrant
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant_data:/qdrant/storage
    environment:
      - QDRANT__SERVICE__HTTP_PORT=6333
      - QDRANT__SERVICE__GRPC_PORT=6334
    networks:
      - ai-agents

  # Backend API
  backend:
    build: 
      context: .
      dockerfile: ./backend/Dockerfile
    container_name: ai-agents-backend
    ports:
      - "8000:8000"
    volumes:
      - ./storage:/app/storage
      - ./src:/app/src
    environment:
      - PYTHONPATH=/app:/app/src
      - QDRANT_HOST=qdrant
      - QDRANT_PORT=6333
    env_file:
      - .env
    depends_on:
      - qdrant
    networks:
      - ai-agents
    restart: unless-stopped

  # Frontend UI
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: ai-agents-frontend
    ports:
      - "8501:8501"
    environment:
      - BACKEND_URL=http://backend:8000
    depends_on:
      - backend
    networks:
      - ai-agents
    restart: unless-stopped

volumes:
  qdrant_data:

networks:
  ai-agents:
    driver: bridge 